USE [master]
GO
/****** Object:  Database [CompanyDataProvider]    Script Date: 07/14/2011 15:44:57 ******/
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'CompanyDataProvider')
BEGIN
CREATE DATABASE [CompanyDataProvider] ON  PRIMARY 
( NAME = N'CompanyDataProvider', FILENAME = N'{0}\CompanyDataProvider.mdf' , SIZE = 8448KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CompanyDataProviderLog', FILENAME = N'{0}\CompanyDataProvider.ldf' , SIZE = 16576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
END
GO
ALTER DATABASE [CompanyDataProvider] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [CompanyDataProvider] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [CompanyDataProvider] SET ANSI_NULLS OFF
GO
ALTER DATABASE [CompanyDataProvider] SET ANSI_PADDING OFF
GO
ALTER DATABASE [CompanyDataProvider] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [CompanyDataProvider] SET ARITHABORT OFF
GO
ALTER DATABASE [CompanyDataProvider] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [CompanyDataProvider] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [CompanyDataProvider] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [CompanyDataProvider] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [CompanyDataProvider] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [CompanyDataProvider] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [CompanyDataProvider] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [CompanyDataProvider] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [CompanyDataProvider] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [CompanyDataProvider] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [CompanyDataProvider] SET  ENABLE_BROKER
GO
ALTER DATABASE [CompanyDataProvider] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [CompanyDataProvider] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [CompanyDataProvider] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [CompanyDataProvider] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [CompanyDataProvider] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [CompanyDataProvider] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [CompanyDataProvider] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [CompanyDataProvider] SET  READ_WRITE
GO
ALTER DATABASE [CompanyDataProvider] SET RECOVERY SIMPLE
GO
ALTER DATABASE [CompanyDataProvider] SET  MULTI_USER
GO
ALTER DATABASE [CompanyDataProvider] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [CompanyDataProvider] SET DB_CHAINING OFF
GO
